
# Use pgsql image postgresql-96-rhel7 as base
FROM registry.access.redhat.com/rhscl/postgresql-96-rhel7

# Copy script for starting pgbench load
COPY start-pgbench-load.sh /root

# set working directory as /root
WORKDIR /root
